### PR TITLE
FIX: issue #3602 (add .gitattributes file)

### PR DESCRIPTION
**Pull request by endo64**
This PR is for #3602 

I've examined [gitattributes](https://github.com/alexkaratarakis/gitattributes) repo and some other [documents](https://help.github.com/en/github/using-git/configuring-git-to-handle-line-endings) and thought that the best way is to set default to auto which Git tries to guess the line endings but also keep the known file extensions in .gitattributes files to be sure they will not be guessed.

I've prepared the list of extensions of all files in the Red repo, made them explicit.

### CODE REVIEW

**Comment by 9214** [comment]
Thanks for taking the initiative @endo64! Minor nitpicking: please follow the contribution [guidelines](https://github.com/red/red/wiki/%5BDOC%5D-Contributor-Guidelines#general-contribution-guidelines) and properly prefix commit messages; in this case, it can be `FIX: issue #3602 (...)`. We follow this convention to make it easier to discern the relevant fixes and features from the commit history.

**Comment by endo64** [comment]
@9214 I've updated the commit message and the title of PR. Thanks for reminding.

**Comment by dockimbel** [comment]
Please change the file name according to my comment https://github.com/red/red/issues/3602#issuecomment-696862733.

**Comment by endo64** [comment]
@dockimbel I've change the file name to `.gitattributes-sample`, didn't touch the `README.md` file, it might be good to note there just like the note `Note: The red git repository does not include a .gitignore file. If you run the automated tests a number of files will be created that are not stored in the repository. Installing and renaming a copy of [.gitignore-sample](https://github.com/red/red/blob/master/.gitignore-sample) file will ignore these generated files.`

**Comment by dockimbel** [comment]
@endo64 Thanks! You can add that note to the README file.

**Pull request merged**
