### PR TITLE
FIX: issue #3658 (argument type for source function is too wide)

### PR DESCRIPTION
**Pull request by meijeru**
This is my first PR. I refer to the discussion on this issue and suppose that the changes are acceptable. If I need to do more, please inform me. I inadvertently added another commit to this same PR. That one is about #3655, which should have been mentioned in the title of this PR.

### CODE REVIEW

**Comment by 9214** [comment]
Why are you adding commits for unrelated issues to same pull-request?

**Comment by meijeru** [comment]
Out of ignorance -- I am just trying to understand Github's PR mechanism. I wanted them to be separaate, but how to do that?

**Comment by 9214** [comment]
By creating a dedicated branch.

**Comment by meijeru** [comment]
But that means a separate branch for each commit that is to be PR'ed?

**Comment by 9214** [comment]
Uhm, no. You can continue to add commits to any branch you want. [Start with the basics](https://git-scm.com/book/en/v2).

**Comment by meijeru** [comment]
Thanks for helping me. Your reference is for Git, though, and I want to work exclusively on the web page. But meanwhile I found how to create new branches. So this mixing of topics will not occur again. If I knew how to delete a commit from a PR I would do that. But I have not found that out yet...

**Comment by greggirwin** [comment]
@meijeru, I'll review tomorrow. In the meantime, know that git is the issue here, and how PRs work, not you. I have this same problem, and it drives me crazy.

**Comment by endo64** [comment]
@meijeru Here is a little help:

Reset your local repo as remote. Be sure that you don't have any other local changes or you will lose them all:

```
git pull upstream master
git reset --hard upstream/master
```

I assume that your `remote`s name is `upstream`, if not, change it to accordingly.

Create new branch, make changes, commit, push and make PR:
```
git branch issue-3658
git checkout issue-3658

<make changes>
git add <files>
git commit -m "FIX: #3658"
git push origin issue-3658
<go to github and make PR>
```

Do the same for the other issue:

```
git checkout master
git branch issue-3665
git checkout issue-3658
<do the same as above>
```

If you do your work on `master` branch and created a PR already, when you make further changes and push them to your fork's master, they will appear on the PR.
PRs are not fixed point in time, if you add more commits to that branch they will appear in the PR.

Hope this helps.

**Comment by endo64** [comment]
One additional note, as you reset master branch as upstream/master, your local master and remote master are not in sync anymore. `master` <> `origin/master`.
So you need to push your local master to origin/master (your fork) by forcing.

`git push -f origin master`

Then they will be in sync.

**Comment by bitbegin** [comment]
why don't you use GitKraken? I have't forgot git command line

**Comment by meijeru** [comment]
Thanks for all your help!

**Pull request merged**
