### PR TITLE
extract/index using block! for pos argument by Heroide

### PR DESCRIPTION
**Pull request by Heroide**
Issue #3248

### CODE REVIEW

**Comment by greggirwin** [comment]
@Heroide thanks so much for the PR! The code looks clean, and you included tests, which is great. The problem is that it also includes `forskip` which is unrelated. I know reworking PRs can be a pain (at least for me), but `forskip`, while useful, has come up a lot in discussion but not yet been approved for inclusion in Red. Tough call. I've used it quite a bit myself in the past. We'll start a wiki page for things intentionally *not* carried over from Rebol and their discussion. 

From there we can decide more formally on `forskip`, and write a full set of tests for it if we decide to include it.

As a side note, `forskip` in R2 was used to make `forall` easy to write, as it's just a special case of `forstkip`. In Red `forall` is a native.

**Comment by Heroide** [comment]
Yes, I did not like that too. Forskip is no good name. But code became messy without. And not working, even more not good. I thought of renaming but now it is more clear where source came from. I understand if forskip is in, people will find out and use. I see the problem.

**Comment by greggirwin** [comment]
On further review, the formatting and some structure seemed odd for Red, and I now see it's basically a paste of the R3 version. With the question I just asked on the original wish ticket behind this, maybe we need to step back and look at `extract`'s design afresh.

**Comment by greggirwin** [comment]
Since `/default` isn't there (which I agree with removing), it's `value` param is now a local, giving us both `val` and `value`, which is confusing.

**Comment by Heroide** [comment]
I removed the bad function. And replaced confusing val and value with better names. Maybe still not Red like, but better.

**Comment by greggirwin** [comment]
Thanks for the updates @Heroide. Let's move the chat to https://github.com/red/red/issues/3248 and look at `extract`'s design, to make sure we're building what we really need.

**Comment by greggirwin** [comment]
I'm closing this, and the related ticket. See the more extensive chat there.

**Pull request closed without merging**
