### PR TITLE
FEAT: convert key to word! when foreach a map

### PR DESCRIPTION
**Pull request by qtxie**

### CODE REVIEW

**Comment by dockimbel** [comment]
Is this PR trying to fix a github ticket?

**Comment by qtxie** [comment]
No. As `keys-of` returns all the keys in a map as `word!`, for the same reason, I made this change.

**Comment by dockimbel** [comment]
But the question then is: why should we allow FOREACH on map? Map has a name/value structure, which is not a good match for FOREACH which is for series...

**Comment by qtxie** [comment]
One use case is that I want to iterate all the key/value pairs in a map! when trying to convert a map! to a JSON object. My first thought is to use `foreach`.

**Comment by rebolek** [comment]
@dockimbel *why should we allow FOREACH on map?* Because it’s convenient:

R3:

```
>> m: map [a: 1 b 2]
== make map! [
    a: 1
    b 2
]

>> foreach k m [print m/:k]
1
2
```

Red:

```
red>> m: #(a: 1 b: 2)
== #(
    a: 1
    b: 2
)
red>> foreach k m [m/:k]
*** Script error: foreach does not allow map! for its 'word argument
*** Where: foreach
```

In R3, `foreach value map []` is a shortcut of `foreach value keys-of map []` and it’s useful.

**Pull request closed without merging**
