### PR TITLE
Add no-trace attr to func spec parser.

### PR DESCRIPTION
**Pull request by greggirwin**

### CODE REVIEW

**Comment by hiiamboris** [comment]
and `[trace]`?

**Comment by greggirwin** [comment]
Ah, yes. Not used in any yet, but will trip `help` as soon as it is. Good catch.

**Comment by toomasv** [comment]
https://github.com/red/docs/blob/master/en/datatypes/function.adoc should also be synchronized?

**Comment by greggirwin** [comment]
Yes, docs should be updated as well.

**Comment by dockimbel** [comment]
@greggirwin You should rebase your PR, as there are unrelated changes in `%environment/tools.red` in it.

**Comment by greggirwin** [comment]
Grrr. Git.

**Pull request closed without merging**
