### PR TITLE
 Add support for get-word!s in `is~`

### PR DESCRIPTION
**Pull request by greggirwin**
lepinekong noted on gitter that this didn't work:
```
portfolio: [
    ["GOOG" 1000 [1018.07 07/12/2017] [1046.67 13/12/2017]]
    ["AAPL" 100 [175.95 18/12/2017] [177.80 19/12/2017]]
    ["FB" 200 [176.29 04/12/2017] []]
]

trade: make reactor! [
    x: 1
    symbol: is [portfolio/:x/1]  ; << This is where the problem lies
 ]
 
view [
    field react [face/data: form trade/symbol]
    button "change" [trade/x: 2]
]
```

I deduced that `symbol: is [pick pick portfolio x 1]` work, then also that `symbol: is [portfolio/(x)/1]`.

### CODE REVIEW

**Comment by greggirwin** [comment]
See also #3147, which was an incomplete version of this.

**Comment by greggirwin** [comment]
Ran all manual reactivity tests from main repo here and ran quick test tests as well. All passed. Will add some new tests for this behavior next.

**Comment by greggirwin** [comment]
Looks like AppVeyor failed because

> Build execution time has reached the maximum allowed time for your plan (60 minutes).

**Comment by dockimbel** [comment]
@greggirwin It's the freezing CALL issue within Rebol which pops up from time to time on Windows platform.

**Comment by dockimbel** [comment]
@greggirwin Your fix seems legit at first look. Do all the tests pass with it?

**Comment by greggirwin** [comment]
My first PR was flawed, but this one seems OK. All quick-test and manual reactive tests pass, and I added new tests for the get-word syntax in the quick-test tests.

**Comment by greggirwin** [comment]
Code was merged, so this PR was effectively accepted. The build failure was apparently due to the R2 `call` issue in running tests.

**Pull request closed without merging**
