### PR TITLE
FEAT: Added test for #4756

### PR DESCRIPTION
**Pull request by rebolek**

### CODE REVIEW

**Comment by hiiamboris** [comment]
Please PR it in a commented out state until we contain all junk files in a temporary directory :D

**Comment by rebolek** [comment]
Fair enough. Some mechanism for dealing with temporary files in tests needs to be introduced. Also, I don’t like using `call` in this test. Any ideas on improving it are welocme.

**Comment by hiiamboris** [comment]
What if you just saved the redbin as a `binary!` and loaded it as `redbin`? That would eliminate the need for `call`

**Comment by hiiamboris** [comment]
Just leave in comments the way to produce the original binary, in case Redbin changes or smth ;)

**Comment by endo64** [comment]
Better to use issue number `4756.red` or `issue-4756.red` instead of generic `test.red` for temporary file name.

**Comment by rebolek** [comment]
> What if you just saved the redbin as a `binary!` and loaded it as `redbin`? That would eliminate the need for `call`

It needs to be loaded in different Red’s instance. The bug doesn’t happen when you don’t restart Red.

**Comment by hiiamboris** [comment]
You didn't get my point :) 
```
load/as #{
52454442494E0204010000006C00000002000000100000000000000008000000
75726C0000000000646174650000000028000000020000000801000000000000
0500000061622F63640000002800000004000000100000020000000090010000
090100000000000012000000687474703A2F2F6578616D706C652E6F72670000
1000000201000000830100002F00000080201D0FC0EFD14000000000
} 'redbin
```
```
*** Runtime Error 1: access violation                                                                                                                                                           *** in file: /D/devel/red/red-src/d2d/runtime/redbin.reds                                                                                                                                       *** at line: 1571                                                                                                                                                                               ***                                                                                                                                                                                             ***   stack: red/redbin/decode-word 02E475D0h 02E47580h 02E479B0h false                                                                                                                         ***   stack: red/redbin/decode-value 02E475D0h 02E47580h 02E479B0h                                                                                                                              ***   stack: red/redbin/decode-value 02E475CCh 02E47580h 02E479B0h                                                                                                                              ***   stack: red/redbin/decode-word 02E475CCh 02E47580h 02E479B0h false                                                                                                                         ***   stack: red/redbin/decode-value 02E475BCh 02E47580h 02E479B0h                                                                                                                              ***   stack: red/redbin/decode-map 02E475BCh 02E47580h 02E47978h false                                                                                                                          ***   stack: red/redbin/decode-value 02E475B4h 02E47580h 02E47978h                                                                                                                              ***   stack: red/redbin/decode-map 02E475B4h 02E47580h 0285F2CCh false                                                                                                                          ***   stack: red/redbin/decode-value 02E47598h 02E47580h 0285F2CCh                                                                                                                              ***   stack: red/redbin/decode 02E47568h 0285F2CCh true                                                                                                                                         ***   stack: ctx||360~decode 0285F2BCh                                                                                                                                                          ***   stack: red/interpreter/exec-routine 0285F2ACh                                                                                                                                             ***   stack: red/interpreter/eval-code 02C168D0h 02D74678h 02D74678h false 02D74658h 02D746A0h 0285F1ECh                                                                                        ***   stack: red/interpreter/eval-path 02D746A0h 02D74668h 02D74678h false false false false                                                                                                    ***   stack: red/interpreter/eval-expression 02D74668h 02D74678h false false false                                                                                                              ***   stack: red/interpreter/eval 0285F29Ch true                                                                                                                                                ***   stack: red/natives/do* true -1 -1 -1                                                                                                                                                      ***   stack: load                                                                                                                                                                               ***   stack: red/_function/call 0285F10Ch 00F63884h                                                                                                                                             ***   stack: red/interpreter/eval-code 02B30408h 02E47650h 02E47650h true 02E47620h 02E47530h 02B30408h                                                                                         ***   stack: red/interpreter/eval-path 02E47620h 02E47630h 02E47650h false false false false                                                                                                    ***   stack: red/interpreter/eval-expression 02E47630h 02E47650h false false false                                                                                                              ***   stack: red/interpreter/eval 0285F0ECh true                                                                                                                                                ***   stack: red/natives/catch* true 1
***   stack: ctx||566~try-do 00F81B74h
***   stack: ctx||566~do-command 00F81B74h
***   stack: ctx||566~eval-command 00F81B74h
***   stack: ctx||566~run 00F81B74h
***   stack: ctx||566~launch 00F81B74h
***   stack: ctx||600~launch 00F812DCh
```
See? No second instance needed ;)

**Comment by rebolek** [comment]
@hiiamboris I see! I’m cold so I’m a bit slower these days :-) Anyways, this is a better test and I going to use it, thanks!

**Comment by dockimbel** [comment]
The issue was related to a Redbin flag that is set during Red boot time. If you would be using the Redbin decoder before the encoder, the flag would not be switched to the right value and it would crash.

**Comment by hiiamboris** [comment]
No Redbin decoding should happen before, or no Redbin *en*coding?

**Comment by dockimbel** [comment]
@hiiamboris _decoding_. The `redbin/codec?` flag is enforced by `redbin/encode`, but not by `redbin/decode`. It controls the Redbin format version to use. When not set (default), it's v1 (used internally by the compiler), when set it's v2 (for general usage). The decoder supports both v1 and v2, the encoder only v2 as the encoding for v1 is done exclusively by the compiler code.

**Pull request merged**
