### PR TITLE
FIX: seeding random with time! and float! issue #4205

### PR DESCRIPTION
**Pull request by loziniak**

### CODE REVIEW

**Comment by hiiamboris** [comment]
@loziniak maybe better `sp/1 xor sp/2`?

**Comment by loziniak** [comment]
I thought about it. But couldn't find any arguments for or against. Do you have any?

**Comment by hiiamboris** [comment]
1) harder to find repeatable seeds (e.g. `Me+N` may produce the same same seed for all N or something alike)
2) big-endian support, where the order of ints within a float is reversed

**Comment by loziniak** [comment]
Isn't it that `sp/1` is always the same as `sp/value`?

**Comment by hiiamboris** [comment]
In my examples - yes. Generally - no.

**Comment by loziniak** [comment]
I misread your first post, didn't notice the *xor*, just thought you want me to replace `sp/value` with `sp/1`, sorry. Sure, xoring is great idea.

**Comment by qtxie** [comment]
@loziniak Nice fix! Thank you! 👍

**Pull request merged**
