### PR TITLE
FEAT: #3738 make cause-error Rebol compatible for string arg

### PR DESCRIPTION
**Pull request by greggirwin**

### CODE REVIEW

**Comment by greggirwin** [comment]
Regression test #1136 throwing an access violation, though it doesn't in the console.
```
	--test-- "#1136"
		e1136: try [load {a: func [][set 'b: 1]}]
		--assert not not all [
			equal? e1136/type 'syntax
			equal? e1136/id 'invalid
			equal? e1136/arg1 lit-word!
		]
```

**Comment by greggirwin** [comment]
Backed out my changes and it still fails with those errors. Something else is amiss.

**Comment by hiiamboris** [comment]
@greggirwin it won't work. Test 1396 on your branch makes a malformed error object because it's arguments (inside a block) weren't reduced:
```
root size: 2239, root max: 4184, cycles: 0
root size: 2239, root max: 4184, cycles: 1
root size: 2239, root max: 4184, cycles: 2
make error! [
    code: 200
    type: 'syntax
    id: 'invalid
    arg1: 'type
    arg2: "5+2)"
    arg3: none
    near: none
    where: 'do
    stack: 3539256
]
```
Then somewhere down the output code it is hardcoded that the error is well formed and it crashes otherwise:
```
*** Runtime Error 1: access violation
*** in file: /D/devel/red/red-src/irwins/runtime/datatypes/object.reds
*** at line: 97
***
***   stack: red/object/rs-select 028AD604h 032C123Ch
***   stack: red/error/reduce 028AD624h 028AD604h
***   stack: red/error/form 028AD604h 028AD614h 028AD5F4h -18
***   stack: red/actions/form 028AD604h 028AD614h 028AD5F4h 0
***   stack: red/actions/form* -1
***   stack: red/natives/prin* false
***   stack: red/natives/print* false
***   stack: red/stack/throw-error 028AD634h
***   stack: red/fire 1 0018FF10h
***   stack: red/type-check 0289DB84h 0 028AD604h
***   stack: --assert
```
You should maybe make a special case for string `args`, instead of compose...
The cause of crash in 1750 is likely the same. 1136 is probably a false success, just a stroke of luck that pointer value occurred within the allocated frame.

**Comment by greggirwin** [comment]
Thanks for digging in @hiiamboris. Hoping to make some time for this today.

**Pull request closed without merging**
