### PR TITLE
FIX: issue #2679 (`prin` does not work correctly with `ask` command)

### PR DESCRIPTION
**Pull request by bitbegin**

### CODE REVIEW

**Comment by qtxie** [comment]
This is a fix for gui-console only.

**Comment by dockimbel** [comment]
@qtxie What's your opinion about this PR now? Should we close it or ask @bitbegin for extra work on it?

**Comment by qtxie** [comment]
I think we have to do big changes in CLI console to fix it. If this PR fixes the issue in gui-console, then it's good to be merged. Just to be sure it won't cause any regression. It's tricky to handle `prin`, need to retest all the `prin & print` issues.

**Comment by bitbegin** [comment]
this fix still not good

**Pull request closed without merging**
