### PR TITLE
FIX: issue #1671 (Drag&drop problems)

### PR DESCRIPTION
**Pull request by qtxie**

### CODE REVIEW

**Comment by rebolek** [comment]
I’m afraid this does not fix #1671 and needs more testing.

**Comment by qtxie** [comment]
It works on my Win7. I will test it on Win10 later.

**Comment by dockimbel** [comment]
@qtxie Works on Win10 now?

**Comment by qtxie** [comment]
Yes. It works on both Win 7 and Win 10 in my test.

**Pull request merged**
