### PR TITLE
FEAT: enable image! in red/core on Linux

### PR DESCRIPTION
**Pull request by qtxie**
Fix issue #4698 and issue #4700.

### CODE REVIEW

**Comment by qtxie** [comment]
Notes this PR will add another dependency (libgdk-pixbuf2.0) in Red/Core on Linux.

**Comment by hiiamboris** [comment]
Just so you know, `sudo apt install libcanberra-gtk3-module:i386` is also required right now (at least on Debian 9 VM), else it spams messages that it can't load this module

**Comment by 9214** [comment]
@qtxie @hiiamboris feel free to update [this](https://github.com/red/red/wiki/%5BNOTE%5D-Linux-GTK-dependencies) page as you deem fit.

**Comment by hiiamboris** [comment]
Oh wow. @9214 I didn't install most of that :D

**Comment by 9214** [comment]
@hiiamboris I did not check if all the dependencies are required, so if it works OK for you, then please remove the ones that are redundant.

**Comment by qtxie** [comment]
> Just so you know, `sudo apt install libcanberra-gtk3-module:i386` is also required right now (at least on Debian 9 VM), else it spams messages that it can't load this module

Yes if you include the view module. It's included by default in red executable unless you use `--no-view`.

**Pull request merged**
