### PR TITLE
Added tests for #2171, #2173, #2181, #2182.

### PR DESCRIPTION
**Pull request by ifgem**

### CODE REVIEW

**Comment by PeterWAWood** [comment]
@ifgem Nenad has asked that tests be formatted in a specific way. Unfortunately, I haven't found the time to write the format down yet. Most of the current tests have been re-formatted in the way Nenad requested but not all yet.

A few of the tests you submitted aren't in the required format. Sorry, about this as you weren't to know.

The two basic formats are:

```
--test-- "one line test"              --assert a == b
```

```
--test-- "multi-line test"
    a: 1
    b: 2
    --assert a == b                     ;; note: --assert is intended from --test--
```

Is it possible for you to adjust the formatting of a few tests in your pull request?

**Comment by ifgem** [comment]
@PeterWAWood I've changed formatting of some tests:)

**Comment by PeterWAWood** [comment]
@ifgem The test you added to function-test.red doesn't compile. The compiler recognises that ```ri10-noexist``` does not exist. Enclosing a value in parentheses does not hide it from the compiler. You can hide it from the compiler by putting it into a block.
For example, change this:
``` 
--assert error? try [ri10-quote (ri10-notexist)]
```
to this:
```
--assert error? try [ri10-quote first [ri10-notexist]]
```

**Comment by PeterWAWood** [comment]
@ifgem  in tests "bak-ext54" and "bak-ext55", you have an assert ```--assert test = none``` which causes a script error. Are you trying to check that the word ```test``` has no value outside of the parse function? If so ```unset? 'test``` would be one correct way of doing so.

**Comment by greggirwin** [comment]
Closing this based on failing to build and age of ticket.

**Pull request closed without merging**
