### PR TITLE
Add base to create-focus-events so that it responds to focus

### PR DESCRIPTION
**Pull request by gltewalt**
Allows for code like this to function

```red
view [
    size 300x300
    base red on-created [set-focus face] on-key [
        switch event/key [
            up    [face/offset/y: face/offset/y - 5]
            down  [face/offset/y: face/offset/y + 5]
            left  [face/offset/x: face/offset/x - 5]
            right [face/offset/x: face/offset/x + 5]
        ]
    ]
]
```

### CODE REVIEW

**Comment by qtxie** [comment]
@gltewalt Thanks! 👍

**Review by qtxie — CHANGES_REQUESTED** [review]
Please remove the gui-console binary file.

**Comment by hiiamboris** [comment]
The fix is working on WSL2

**Comment by gltewalt** [comment]
> Please remove the gui-console binary file.

Sorry about that. 
I don't have permissions to delete it here... I'm not sure how to fix this unless I do a new PR

**Comment by hiiamboris** [comment]
`git rm` `git commit` `git push`?

**Comment by gltewalt** [comment]
> `git rm` `git commit` `git push`?

Ah, yes... the joys of fading memory. Thanks.

**Comment by hiiamboris** [comment]
Seemingly that didn't work ;)

**Comment by gltewalt** [comment]
Closing and submitting new PR

**Pull request closed without merging**
