### PR TITLE
3502

### PR DESCRIPTION
**Pull request by hiiamboris**
Fix for the notorious https://github.com/red/red/issues/3502

As to the cause - why the input from the pipe is not immediately available after the process just terminated, figure it probably how the buffering in Windows works. It terminates then writes the buffer into pipe, and we are able to peek at it before the flush. 

I can't simply use `until [.... remain: remain - written   remain <= 0]` there, as what if the pipe holds exactly 10000 bytes (the buffer size)? Then the next ReadFile will try to wait for a write on that pipe which will never occur.

### CODE REVIEW

**Comment by greggirwin** [comment]
NICE! I know Nenad will want the unrelated caret/ceiling commits omitted if possible. Git causes me grief this way too, but if you can remove those from the PR, I will merge this ASAP.

**Comment by hiiamboris** [comment]
@greggirwin these are already merged into the master branch. I have no idea why git lists these.

**Comment by greggirwin** [comment]
Ah, git.

**Comment by endo64** [comment]
Those commits looks in `3502` branch in `hiimboris/red` and merged into red from there. But they are not in master branch `hiiamboris/red`. I think you need to pull first.

**Comment by endo64** [comment]
Couldn't reach @greggirwin 's speed :)
But anyway, it is always a good practice to pull from the upstream/master into your master when your PRs merged into it, before making other changes in your fork.

**Comment by hiiamboris** [comment]
@endo64 that's what I did when it added the "Merge branch 'master' of https://github.com/red/red into 3502" commit.

**Comment by qtxie** [comment]
I usually use `git pull --rebase` to avoid the extra `Merge branch 'master'` commit.

**Comment by hiiamboris** [comment]
@qtxie thanks! I'll keep that in mind.

**Pull request merged**
