### PR TITLE
Added SCALAR? and IMMEDIATE?

### PR DESCRIPTION
**Pull request by greggirwin**

### CODE REVIEW

**Comment by greggirwin** [comment]
So you don't want tests that would catch typeset changes? i.e. those are not considered regressions?

**Comment by dockimbel** [comment]
If we change the typesets definitions, it will be for good reasons, having to maintain such tests is double work.

**Comment by PeterWAWood** [comment]
I think it would be a good idea to have just two tests, one positive, one negative for each of the functions just to confirm the function is working. The other tests are ideally redundant as they should  be duplicate of typeset tests.

**Comment by greggirwin** [comment]
I understand, don't agree entirely, but OK. Not worth your time right now. Go ahead and close this. Or do I need to since it's not being merged?

**Comment by dockimbel** [comment]
@greggirwin You can just add another commit to change the tests part. The functions definitions are fine.

**Comment by greggirwin** [comment]
Done.

**Comment by dockimbel** [comment]
@greggirwin Thanks. I can't merge it as there's a conflict now (not sure from where it comes from).

**Comment by dockimbel** [comment]
Conflict is gone, merging now.

**Pull request merged**
