### PR TITLE
FIX: issue #3511 (line is a special arg, should return a copy of it)

### PR DESCRIPTION
**Pull request by bitbegin**

### CODE REVIEW

**Comment by greggirwin** [comment]
Appveyor seems to have hung. This is a safe and small change, so I'll merge it. Travis passed.

**Comment by qtxie** [comment]
It is a bit strange. Should not need to copy the line as `ask` works fine in the console engine.

**Comment by qtxie** [comment]
If it's needed, better to use `move` to move the content to the head of the string, avoid making a new string.
As we have GC now, it is not a big issue.

**Comment by qtxie** [comment]
@bitbegin It's not the right fix. The bug is in `print`, not in `ask`.
```
>> s: skip "enter your name Sam" 16
== "Sam"
>> s
== "Sam"
>> print s
enter your name Sam
```

**Comment by bitbegin** [comment]
@qtxie i'll fix it

**Comment by qtxie** [comment]
Why not just remove the `head`?

**Comment by bitbegin** [comment]
https://github.com/red/red/blob/04f07dfc243d8e1bc2f363287704f21bf66fc63f/environment/console/GUI/core.red#L625  like here, the line at tail but include promote.

**Comment by qtxie** [comment]
Then we should add a `head` there: `add-line head line`. It's not efficient and would be costly to copy the string each time we printing.

**Comment by bitbegin** [comment]
@qtxie please review this https://github.com/red/red/pull/3514

**Comment by qtxie** [comment]
Looks good to me. :+1

**Pull request merged**
