### PR TITLE
FIX: increased tolerance for antialiased text color

### PR DESCRIPTION
**Pull request by hiiamboris**

### CODE REVIEW

**Comment by greggirwin** [comment]
What about `/within` rather than `/tol` ?

**Comment by hiiamboris** [comment]
Does it matter?

**Comment by greggirwin** [comment]
Naming always matters, unless you're the only one who ever has to look at it.

**Comment by hiiamboris** [comment]
Whole test system needs redesign from scratch. And this test's lifecycle will end once we get to View improvements. I'd rather not put lipstick on a pig.

**Comment by greggirwin** [comment]
Please don't make this someone else's fault. Every choice can make things better or worse. Should we not always strive to write the best code we can? What kind of code and projects do you appreciate and respect? What do we want people to think about Red?

**Comment by hiiamboris** [comment]
I just prefer to spend my time where it adds value is all :)

**Comment by greggirwin** [comment]
So always give things good names to start with.

**Comment by hiiamboris** [comment]
Indeed. I took note of your critique and agree with it.

**Pull request merged**
