### PR TITLE
prevent #3607-like regressions

### PR DESCRIPTION
**Pull request by hiiamboris**
A test file for draw image. Let me know if I'm checking for View availability in a wrong manner.

### CODE REVIEW

**Comment by qtxie** [comment]
@hiiamboris A better way is to use macros. 
```
#if find config/modules 'view [
    ;-- tests
]
```

**Comment by hiiamboris** [comment]
@qtxie unfortunately the testing framework won't allow this:
```
source/units/auto-tests/run-all-comp2.red - compiler error


-=== Red Compiler 0.6.4 ===-

Compiling D:\devel\red\red-src\red\tests\source\units\auto-tests\run-all-comp2.red ...
...using libRedRT built on 26-Nov-2018/22:23:13
*** Preprocessor Error in #if
*** Script Error : find expected series argument of type: series object port bitset
*** Where: [#if]
*** Near:  [find config/modules 'view]
```

**Comment by greggirwin** [comment]
@qtxie in cases where one CI path fails (e.g. Travis), but the other succeeds, do we want to hold off merging? Appveyor almost always fails due to timing out, so I merge if that's the case.

**Comment by qtxie** [comment]
@greggirwin I also think it's safe to merge the PR in this case.

**Comment by hiiamboris** [comment]
But it was broken :( I'll try to find the time tomorrow to fix it.

**Pull request merged**
