### PR TITLE
FEAT: #2518 Add EVEN?/ODD? support to percent!

### PR DESCRIPTION
**Pull request by greggirwin**

### CODE REVIEW

**Comment by dockimbel** [comment]
Could you please please rebase your PR to avoid all those unrelated commits?

**Comment by greggirwin** [comment]
Rebasing to upstream was what created them. :^\ I'll give it another shot.

**Comment by greggirwin** [comment]
I have a couple commits doubled again after syncing and merging. :^( Do you want me to see if I can squash those without screwing anything up?

**Comment by dockimbel** [comment]
No need for squashing, I'll take them as-is.

**Pull request merged**
