### PR TITLE
FIX: issue #3659 COMPOSE should only accept block! argument

### PR DESCRIPTION
**Pull request by meijeru**

### CODE REVIEW

**Comment by meijeru** [comment]
I don't know why I always get the merge request combining into my PR.

**Comment by greggirwin** [comment]
Errors from runners in %red/tests/source/units/auto-tests, which will likely boil down to errors in %run-all/evaluation-test.red, since you changed `compose`. Looks like there are some non-block tests that need to go away. Look for "; non-block args (non-evaluating)"

**Comment by hiiamboris** [comment]
@meijeru you can run these tests locally with:
`rebol --do "do/args %red.r {tests\source\units\auto-tests\run-all-interp.red} quit"` and
`rebol --do "do/args %red.r {-r tests\source\units\auto-tests\run-all-comp1.red} quit" & run-all-comp1`
Before you do, insert a `qt-verbose: yes` line after the `#include %......quick-test.red` so you'll see exactly on what test it tripped.

**Comment by greggirwin** [comment]
@hiiamboris, thanks for reminding me about qt-verbose as well. I had forgotten already.

**Comment by meijeru** [comment]
Why could it still be failing?

**Comment by meijeru** [comment]
Found another test using compose!

**Comment by hiiamboris** [comment]
@meijeru to make it regression proof you might want to add some tests like `error? try [compose 1]` or alike.

**Comment by greggirwin** [comment]
Still failing it seems, but "Removed suprtflupis test" typo made me laugh out loud. :^)

**Comment by meijeru** [comment]
Yes, the typo was hilarious. Now I found one more test, not marked as "non-block" but still one of those.
This time around it should work....

**Comment by meijeru** [comment]
Now Travis has a time-out, apparently on fetching some Debian stuff. 😢

**Comment by greggirwin** [comment]
Hmmm, usually it's Appveyor that times out. Since Appveyor passed, I think we're OK. Just be on the alert if someone posts a related issue.

**Pull request merged**
