### PR TITLE
FIX: issue #4575 - (Add (modified if string)...)

### PR DESCRIPTION
**Pull request by theSherwood**

### CODE REVIEW

**Comment by 9214** [comment]
FYI, `DOCS` label is [reserved](https://github.com/red/red/wiki/%5BDOC%5D-Contributor-Guidelines#general-contribution-guidelines) for issues directly related to `red/docs` documentation. If PR addresses a ticket, then `FIX: issue #<number> (<description>)` format should be used.

For the fix itself, I propose to use "modified when series" instead, since we have at least one precedent with it:
https://github.com/red/red/blob/696ae437550711ba8df46dc611ae12e9f156b0f0/environment/actions.red#L26

OTOH, some functions note that in their top-level docstring:
https://github.com/red/red/blob/696ae437550711ba8df46dc611ae12e9f156b0f0/environment/functions.red#L211-L212

And others in return docstring:
https://github.com/red/red/blob/696ae437550711ba8df46dc611ae12e9f156b0f0/environment/functions.red#L551

Consistency is surely lacking.

**Comment by theSherwood** [comment]
That's good to know. I figured "Docs" would make sense on account of the issue being tagged with `type.documentation`. But that makes sense. Shall we close this and I can open another pull request that is correctly named?

**Comment by 9214** [comment]
@theSherwood no need! It's just me being overly pedantic 😸

**Comment by theSherwood** [comment]
Okay. I'll be sure to make that change to the docstring when I next get the chance.

**Pull request merged**
