### PR TITLE
FEAT: Add NetBSD target

### PR DESCRIPTION
**Pull request by vazub**
Successfully ported Red to NetBSD (x86, non-GUI console). Everything seems to work well so far. 

The only caveat is that you need NetBSD/i386 to run it, as NetBSD/amd64 lacks 32-bit libcurl in binary packages. You could probably build 32-bit libcurl manually and place it properly for multiarch setup (NetBSD supports this in general), but this is distro-specific effort and not related to the porting part itself.

P.S. Yet again, seemingly lots of changes, although the majority of them are whitespace (LF/CRLF) related, please ignore those when diffing.

### CODE REVIEW

**Comment by dockimbel** [comment]
Nice work! Especially on getting the linker compatible with NetBSD. If you would remove the auto-trimming of tail whitespaces and rebase your branch against the latest master, I would be glad to merge it, and promote it! ;-)

**Comment by dockimbel** [comment]
@vazub Thanks for the quick changes!

Could you please rebase your PR branch against master and fix the conflicts?

**Comment by vazub** [comment]
@dockimbel Terribly sorry for my ignorance, but I am not sure I fully understand the request about rebasing. I was assuming my branch has already been updated to the latest red/master with the commit above - d38858e, and GitHub says there are no conflicts with the base branch, all checks passed. Am I missing something here?

**Comment by dockimbel** [comment]
@vazub I'm not sure what's wrong, but I can't merge the PR from Github interface:

image

**Comment by vazub** [comment]
Superceded by https://github.com/red/red/pull/4656, hopefully that one will merge fine.

**Pull request closed without merging**
