### PR TITLE
Issue 2586 fix

### LINKED ISSUE #2586: Exclude percent! from trig functions
Today the trig funcs use `number!`, which includes `percent!`. Change to `integer! float!` in their type signatures. Percent support is not by design.

### PR DESCRIPTION
**Pull request by hiiamboris**
Fixes #2586

### CODE REVIEW

**Comment by greggirwin** [comment]
Hmmm. Appveyor failed, but not due to a timeout.

**Comment by greggirwin** [comment]
Interpreter test failure.

**Comment by hiiamboris** [comment]
I cannot reproduce the test failure on W7 PC & W10 VM. Can't help it ):

**Comment by greggirwin** [comment]
Post to Gitter, and see if someone on Linux is willing to test.

**Comment by hiiamboris** [comment]
But it's the AppVeyor failing. On Windows Server 2012 I think.

**Comment by greggirwin** [comment]
Rats. I thought that one was Linux.

**Comment by dockimbel** [comment]
@hiiamboris You have excluded `float!` from the type spec of arguments to many action's refinements, but that is a regression. Both Rebol and Red allow decimal (float) values for `/part` or `/seek` refinements. Such values are internally rounded (floored) to integer.

**Comment by greggirwin** [comment]
@dockimbel though it's technically a regression, is `float!` support for `/part` a useful feature? I don't recall ever using it (anecdotal), but it also seems like it could lead to gaps in processing, unless you also round and track separately. e.g. some chunking loop ends up exactly on a whole number after chunks that aren't.

**Comment by hiiamboris** [comment]
Can I get a single example of an action (in Red or Rebol) that successfully accepts (no error thrown) a float! part argument and returns an expected result?

**Comment by 9214** [comment]
@hiiamboris would you like to follow through with this one? I propose to implement trig changes only (as was requested in the original ticket), and factor-out `action!` changes into a separate PR, for design discussions (e.g. in the light of recent changes to iterators that can now accept `float!` counters).

**Comment by hiiamboris** [comment]
I'll see what I can do.

**Comment by hiiamboris** [comment]
I also think actions changes will require a bit R/S work. And that should be done *after* the #4097 merge. `/part`, `/dup`, `/skip`, `/seek` and `sort/compare <number>` are possible targets.

**Comment by 9214** [comment]
@hiiamboris does your PR contains anything related to `/skip` semantics? I'm in the process of granting #3004 and bottomed down on `sort/skip` behavior as a reasonable default.

**Comment by hiiamboris** [comment]
No, I just *removed* percent and float. But if we're *adding* float, it should be done everywhere, not in random places.

**Comment by 9214** [comment]
@hiiamboris sorry, I meant `/skip` in #4097 and proposed series model, not this PR.

**Pull request closed without merging**
