### PR TITLE
An alternate way to create Red binary

### PR DESCRIPTION
**Pull request by qtxie**
This PR contains a script to create Red binary without using Rebol SDK. The created executable has the same features as the current one, plus some advantages:

1. Use red.exe from system path (fix issue #3562 #543, #1547)
2. Use red.exe immediately after downloaded, no precompiling needed.
3. More friendly to the OS's package manager (APT, YUM, etc.)
4. Maybe we can sign it to avoid warning of some Anti-virus software.

Here are the prebuilt binaries for testing:
[red-win.zip](https://github.com/red/red/files/5614742/red-win.zip)
[red-linux.zip](https://github.com/red/red/files/5614746/red-linux.zip)
[red-mac.zip](https://github.com/red/red/files/5614747/red-mac.zip)

### CODE REVIEW

**Comment by hiiamboris** [comment]
`--cli` doesn't work for me on W10
Also, it's 400kB bigger now.

**Comment by greggirwin** [comment]
On PR#4739 GH won't let me upload the signed, zipped version in a comment it seems. Signed version works fine. Since our cert is Redlake's, that's who will show. I think this is OK, as Redlake is there to support Red. We may just want to note that somewhere. GH won't even let me comment now.

**Comment by greggirwin** [comment]
Comment finally posted. Let me try uploading again.

**Comment by greggirwin** [comment]
[red-win-signed.zip](https://github.com/red/red/files/5618676/red-win-signed.zip)

**Comment by qtxie** [comment]
@greggirwin Thanks. :+1: Only two Anti-Virus tools report warning after signed. https://www.virustotal.com/gui/file/747251168d2058dbe8eeef9e6c72aed08739401170b92c9b66d54b22048fcb31/detection

**Comment by qtxie** [comment]
> From the code it looks like only a single prebuilt console is included. By design?

Yes. Actually I'm not sure which way is better: A single binary includes all versions of the console or several downloading options. I was prefer the later. 
* The big red button on the download page on red-lang.org provide the standard version (CLI console + View module)
* An alternate download for GUI version (red-gui.exe, GUI console + View module)
* An alternate download for Core version (red-core.exe, CLI console, No view module)

I'm not sure how many users need `--cli`. We could support it. But is it worth to add it if it's too complicated and tricky?

**Comment by qtxie** [comment]
@hiiamboris
> Also, only works with Rebol/Core. Rebol/View doesn't work.

What's the error you got? Rebol/View works fine in my test.

**Comment by hiiamboris** [comment]
> 
> 
> @hiiamboris
> 
> > Also, only works with Rebol/Core. Rebol/View doesn't work.
> 
> What's the error you got? Rebol/View works fine in my test.

It just quits silently. Tested on Rebol/View 2.7.8.3.1 (not the 2.7.6. used by CI)

**Comment by litew** [comment]
> * An alternate download for Core version (red-core.exe, CLI console, No view module)

Just 2 cents. I'll vote for this too as this option is just perfect for deploying Red on servers without any GUI-toolkits installed.

**Comment by dockimbel** [comment]
I don't like that the `%engine.red` has been filled with unrelated functions. They should go in a separate file.

**Comment by qtxie** [comment]
Use separated Red binaries now. This is not needed.

**Pull request closed without merging**
