### PR TITLE
FIX: extend support of MAP! keys to new datatypes.

### PR DESCRIPTION
**Pull request by 9214**
`ref!` and `money!` are now both allowed.

### CODE REVIEW

**Comment by 9214** [comment]
Local tests:
```
This test started at 28-May-2020/19:37:59.563+2:00
Complete Red Test Suite

ok - lexer...........................................34 / 34
ok - lexer-auto......................................18 / 18
ok - unicode.........................................67 / 67
ok - preprocessor tests..............................39 / 39
ok - run-all-comp1.red.............................7809 / 7809
ok - run-all-comp2.red.............................5244 / 5244
ok - run-all-interp.red...........................12909 / 12909
ok - tools............................................7 / 7
ok - Red print.......................................13 / 13
ok - Red run time errors..............................9 / 9
ok - Red compile errors...............................7 / 7
ok - base-self......................................493 / 493
ok - alias-compile....................................3 / 3
ok - cast-compile....................................28 / 28
ok - comp-err.........................................2 / 2
ok - exit-err.........................................3 / 3
ok - int-literals-err.................................1 / 1
ok - output...........................................3 / 3
ok - return-err.......................................5 / 5
ok - conditions-required-err.........................23 / 23
ok - inference-err....................................1 / 1
ok - callback-err.....................................2 / 2
ok - infix-compile....................................3 / 3
ok - not-compile......................................1 / 1
ok - print............................................3 / 3
ok - enumerations compile............................12 / 12
ok - pointer-compile..................................2 / 2
ok - namespace compiler tests.........................9 / 9
ok - compiles-ok......................................1 / 1
ok - dylib compiler...................................2 / 2
ok - define...........................................1 / 1
ok - Red/System Compiler Regression tests...........107 / 107
ok - array............................................2 / 2
ok - logic..........................................105 / 105
ok - byte..........................................3677 / 3677
ok - c-string........................................20 / 20
ok - struct.........................................571 / 571
ok - pointer.........................................75 / 75
ok - cast...........................................144 / 144
ok - alias...........................................23 / 23
ok - length..........................................11 / 11
ok - null............................................11 / 11
ok - enum............................................19 / 19
ok - float.........................................1683 / 1683
ok - float32.......................................1085 / 1085
ok - lib.............................................15 / 15
ok - get-pointer.....................................28 / 28
ok - float-pointer...................................61 / 61
ok - namespace......................................112 / 112
ok - not.............................................44 / 44
ok - size............................................38 / 38
ok - function.........................................6 / 6
ok - case............................................64 / 64
ok - switch..........................................85 / 85
ok - exit.............................................9 / 9
ok - return..........................................25 / 25
ok - exceptions......................................11 / 11
ok - modulo..........................................29 / 29
ok - math-mixed....................................1775 / 1775
ok - infix............................................2 / 2
ok - conditional.....................................15 / 15
ok - system..........................................16 / 16
ok - atomic...........................................8 / 8
ok - queue...........................................64 / 64
ok - dylib-auto.......................................7 / 7

ok - Complete Red Test Suite......................36707 / 36707
       in 0:11:01.482
```

**Comment by meijeru** [comment]
Curiously, the spec (at least in my version) always said: `scalar!, any-word!, any-string! or binary!`. This fix makes that actually true. The problem here was that the defined typesets (TYPE_ANY_STRING etc. ) were not used and that gives a maintenance problem. I could therefore plead for TYPE_SCALAR as an additional `#define`.

**Comment by dockimbel** [comment]
Are `money!` and `ref!` types supported by the hashing code?

**Comment by 9214** [comment]
@dockimbel `ref!` is, I can add support for `money!` but don't know how to account for sign bit in the header.

**Comment by qtxie** [comment]
It's good to be merged.

**Comment by 9214** [comment]
@qtxie `money!` support for hashing code is still pending. I'll work on it after the weekend.

**Comment by 9214** [comment]
@qtxie [it is done!](https://www.youtube.com/watch?v=dmZYbyqLLZU). I defined `ALL_WORD` and `ALL_WORD?` supporting macros, but did not implement support for `issue!` and `refinement!`, since your PR does that. Please review the changes once again, and if it's OK, then we are good to go.

**Comment by greggirwin** [comment]
Thanks both!

**Pull request merged**
