### PR TITLE
FEAT: Win: adds read-only flag for AREA face

### PR DESCRIPTION
**Pull request by qtxie**
view [area 100x100 read-only "1some text some text^/2some text some text^/3some text some text^/4some text some text^/5some text some text^/6some text some text^/7some text some text^/8some text some text^/9some text some text"]

### CODE REVIEW

**Comment by dockimbel** [comment]
What about the other GUI backends?

**Comment by dockimbel** [comment]
I'm not in favor of this platform-specific option leaking up to VID level. I would prefer a generic platform-independent way in VID/View to disable keyboard keys input on widget where such inputs produce changes.

**Comment by hiiamboris** [comment]
One can edit an area with a pointing device (by selecting things and right click menu).

**Comment by qtxie** [comment]
> What about the other GUI backends?

The `area` control has a `read-only` mode on other GUI backends too. 

> I would prefer a generic platform-independent way in VID/View to disable keyboard keys input on widget where such inputs produce changes.

Yes. That's a better way.

**Pull request closed without merging**
