### PR TITLE
Improve view

### PR DESCRIPTION
**Pull request by qtxie**
Using hardware acceleration causes problems on some systems. For example, the Edge browser and the Red gui-console are both flickering on my Win10. Turn off the hardware acceleration fix it.

### CODE REVIEW

**Comment by dockimbel** [comment]
> For example, the Edge browser and the Red gui-console are both flickering on my Win10. 

Could it be just an issue in the graphic card driver?

**Comment by dockimbel** [comment]
The changes you've made in %style.red seems to be Windows-specific, while those definitions should be cross-platform...

**Comment by hiiamboris** [comment]
Shouldn't default height be inferred from the system font height?

**Comment by qtxie** [comment]
> 
> 
> > For example, the Edge browser and the Red gui-console are both flickering on my Win10.
> 
> Could it be just an issue in the graphic card driver?

Yes. I think so. I have updated to the latest driver and installed all the updates for Windows, but no help.

**Comment by dockimbel** [comment]
> Shouldn't default height be inferred from the system font height?

We need to switch to a dynamic coordinate system, but that's a pretty big design and refactoring effort that I was planning to do along the work on Android backend.

**Comment by qtxie** [comment]
> Using hardware acceleration causes problems on some systems. For example, the Edge browser and the Red gui-console are both flickering on my Win10. Turn off the hardware acceleration fix it.

Close it now. Looks like only my desktop has this issue, no other users complained about it.

**Pull request closed without merging**
