### PR TITLE
Foreach map

### PR DESCRIPTION
**Pull request by qtxie**
```
m: #(a 1 b 2 c 3)
foreach [k v] m [print [k v]]
```
Will output: 
```
a 1
b 2
c 3
```

### CODE REVIEW

**Comment by greggirwin** [comment]
Allowing mod 2 sizes for iterator words is cool, but also makes me a little uneasy. It comes back to whether we want to guarantee key ordering. I suppose there are algorithms that could use it, and be safe because they're independent of order (commutative). @dockimbel, thoughts?

**Comment by dockimbel** [comment]
We will stick with an argument block of strictly 2 words for maps.

**Comment by greggirwin** [comment]
Will merge later today, if nobody says otherwise. And I'll find the ticket related to this.

**Comment by greggirwin** [comment]
https://github.com/red/red/issues/2279 is the old wish ticket.

**Pull request merged**
