### PR TITLE
FEAT: supports issue! and refinement! as key in map.

### PR DESCRIPTION
**Pull request by qtxie**

### CODE REVIEW

**Comment by 9214** [comment]
https://github.com/red/red/pull/4474

**Comment by hiiamboris** [comment]
You got refinement twice there - in ALL-WORD and separately as TYPE_REFINEMENT

**Comment by dockimbel** [comment]
@qtxie Please also review #4474.

**Comment by qtxie** [comment]
> You got refinement twice there - in ALL-WORD and separately as TYPE_REFINEMENT. And TYPE_ISSUE too.

I don't get it. TYPE_ALL_WORD and TYPE_REFINEMENT are in different functions.

**Comment by hiiamboris** [comment]
Right ;) My mistake.

**Comment by greggirwin** [comment]
@qtxie, are we merging this, #4474, or both?

**Comment by qtxie** [comment]
@greggirwin Both. But #4474 is not finished yet.

**Pull request merged**
