### PR TITLE
FEAT: Unboring `attempt`

### PR DESCRIPTION
**Pull request by hiiamboris**
Tried a few variants, but paths win over apply:
```
attempt1: func [
	"Tries to evaluate a block and returns result or NONE on error"
	code [block!]
	/safer "Capture all possible errors and exceptions"
][
	; apply 'try/:all [[return do code] safer]     ;-- same
	apply/all :try [[return do code] safer]
	none
]

attempt2: func [
	"Tries to evaluate a block and returns result or NONE on error"
	code [block!]
	/safer "Capture all possible errors and exceptions"
	/local all
][
	set 'all safer										;-- `all:` refuses to compile
	try/:all [return do code]
	none
]

clock/times [attempt []] 1e6
clock/times [attempt1 []] 1e6
clock/times [attempt2 []] 1e6
```

```
0.92 μs [attempt []]
0.89 μs [attempt1 []]
0.41 μs [attempt2 []]
```
Unfortunately on failure it's still slow and presses GC a lot by spawning errors and then discarding them.

### CODE REVIEW

**Comment by dockimbel** [comment]
@hiiamboris Did you see those errors? https://ci.appveyor.com/project/red/red/builds/47236355

**Comment by hiiamboris** [comment]
> We could make a native `attempt` implementation or add a new refinement to `try` to avoid the creation of the error object. Though, feasibility would need to be confirmed.

https://github.com/red/REP/issues/113 addition will significantly lower the need for fast `attempt`. So let's not chase it yet.


> @hiiamboris Did you see those errors? https://ci.appveyor.com/project/red/red/builds/47236355

I'll take a look.

**Comment by hiiamboris** [comment]
@dockimbel still trying to isolate it, but it's some compiler crap. When I compile `-c` the `run-all-interp.red`, it works, when I `-r` it it fails with `bitset has no value` or smth like that (and there's no word `bitset` in the file, only `bitset!`).

**Comment by dockimbel** [comment]
@hiiamboris You've made a typo. In `try/:all [return do code]`, `code` is not defined. You should rename the `value` argument to `code`.

**Comment by hiiamboris** [comment]
Oh of course copy-paste problems :D

**Comment by hiiamboris** [comment]
I'll PR it.

**Pull request closed without merging**
