### PR TITLE
Complex pen

### PR DESCRIPTION
**Pull request by Zamlox**
Implementation of complex pen as described [here](https://github.com/qtxie/red/wiki/Create-Complex-Pen-in-Draw). Only Windows platform GDI+ backend

### CODE REVIEW

**Comment by Zamlox** [comment]
Yes, indeed. They are powerful. I like most the 'pattern' because it allows to define patterns recursively using  draw commands.

**Comment by Oldes** [comment]
cool!

**Comment by DideC** [comment]
Need a good demo to demonstrate it now !

**Comment by Zamlox** [comment]
For now, only the test is available: tests/complexpen-test.red
Any other ideas for a good demo ?

**Pull request merged**
