### PR TITLE
FEAT: issue #2513 - providing information about console width in the …

### PR DESCRIPTION
**Pull request by Oldes**
…CLI mode

### CODE REVIEW

**Comment by dockimbel** [comment]
All platforms should behave the same way, this feature needs to be done for all platforms supported or none.

**Comment by Oldes** [comment]
With this modification, the `system/console/size` is newly updated in CLI version when user changes size from properties menu.

**Comment by Oldes** [comment]
@dockimbel it should be possible to add this feature to other platforms. See http://stackoverflow.com/a/1022961/494472

**Comment by Oldes** [comment]
@qtxie could you please test if the POSIX change from the last commit is correct.. I have just Windows available now so it was a blind change.

**Comment by dockimbel** [comment]
@qtxie Please review the changes in this PR.

**Comment by Oldes** [comment]
There is still one issue... at this moment the CLI version reports size as a size of buffer and not the screen as it is in the GUI version... I think it should be changed as the second is more useful. I will do it soon.

**Pull request merged**
