### PR TITLE
FIX: issue #5108 (Extra block copy in make map!)

### PR DESCRIPTION
**Pull request by ALANVF**
Seemed simple enough, though I'm not super experienced with R/S so I might've missed something

### CODE REVIEW

**Comment by dockimbel** [comment]
Your fix seems fine, `block/copy` relies on `_series/copy` which are parts of `copy` action implementation, so higher-level than `block/clone`, but for this use-case, I don't see any difference in behavior.

I only reviewed the code I didn't test it. Did you run the tests from #5108 to check the fix efficiency?

**Comment by ALANVF** [comment]
I ran the test used for looking at the allocated memory, and it appeared to be fixed by my changes

**Comment by hiiamboris** [comment]
We also usually add regression tests (see any other PR).

**Comment by ALANVF** [comment]
I know, but this was small enough that I didn't think it was necessary

**Comment by greggirwin** [comment]
A lot of changes seem that way, but they all add up. It's also possible that someone will come along later and remove the copy ("Hey, I optimized something!"), unless it's clearly documented that it's needed. Since there are no comments, which are also good to add, because that informs future work that may be based on code, tests seem like a good idea.

**Comment by dockimbel** [comment]
In general, we require regression tests for PRs that are fixing bugs. Though, we can skip the test for this kind of code improvement, which is not a bug, just inefficient implementation. Remember this is v0.6.4 and still many design decisions are not yet made or are subject to change until 1.0. So let's not waste time on writing tests for such cases, on code that might be gone in the future.

**Pull request merged**
