### PR TITLE
Install Red in Cloud9 IDE

### PR DESCRIPTION
**Pull request by gltewalt**

### CODE REVIEW

**Comment by dockimbel** [comment]
Thanks for documenting it! :+1:  Though, such documentation should rather go into the Red wiki. From there, we can link that page from the README and the Red web site.

**Comment by gltewalt** [comment]
Which section of the Wiki should it be in?

**Comment by dockimbel** [comment]
Just create a wiki page for it, and post the link in red/docs chatroom to @scaremonger and @dockimbel.

**Comment by gltewalt** [comment]
Done.

**Pull request closed without merging**
