### PR TITLE
FIX: issue #3252 (RANDOM doesn't use /time part of date! seeds)

### PR DESCRIPTION
**Pull request by hyzwhu**

### CODE REVIEW

**Comment by hyzwhu** [comment]
@greggirwin  I tested it with release mode, it ran successfully and returned the expected results.

**Comment by greggirwin** [comment]
What I mean is, we need tests included in the quick-test suite, to confirm that it continues to work, regressions are caught, and no regressions are caused.

**Comment by greggirwin** [comment]
https://github.com/red/red/blob/master/tests/source/units/date-test.red  is where other `date` `random` tests are, so that's the place to add new tests.

**Comment by greggirwin** [comment]
I'll go ahead and merge this PR, and you can make another for the tests. Thanks!

**Comment by greggirwin** [comment]
@hyzwhu, @endo64 added a fix and a couple tests for this as it didn't work as expected. In the future, we'll probably be stricter about requiring tests with PRs.

**Pull request merged**
