### PR TITLE
FEAT: remove `matrix-order` command in DRAW.

### PR DESCRIPTION
**Pull request by qtxie**
This feature is GDI+ specific, rarely used and not easy to be implemented on other platforms.

### CODE REVIEW

**Comment by qtxie** [comment]
Changes in docs: https://github.com/red/docs/pull/240

**Comment by 9214** [comment]
https://github.com/red/red/pull/4450

**Comment by dockimbel** [comment]
@qtxie Seems it is implemented for macOS by PR #4450. Is it possible to support it on GTK also somehow?

**Comment by qtxie** [comment]
@qtxie Yes. It can be implemented. The reasons to remove it:
* It's based on a GDI+ specific feature, I don't see other graphic frameworks provide it. 
* It's not a necessary feature, almost nobody use it.
* Reduce the performance of all the drawing commands on non-Windows platforms. (Check the implementation on macOS, every draw commands need a `ctx-matrix-adapt` and `ctx-matrix-unadapt` in order to support it)

**Comment by dockimbel** [comment]
@qtxie Ok, so we'll drop it.

**Pull request merged**
