### PR TITLE
2191 pt1

### PR DESCRIPTION
**Pull request by hiiamboris**
https://github.com/red/red/pull/3638 description was here
Any idea why travis is ignoring this PR?

### CODE REVIEW

**Comment by hiiamboris** [comment]
Now this is fantastic. All tests succeed on my W7 and Xubuntu VM.

**Comment by greggirwin** [comment]
I tagged Peter to review this, though he may not have time right now. Per some other test chat, we'll plan for more test changes, to minimize runtimes. But adding tests is almost always a good thing, as long as we don't have redundant tests just wasting time.

**Comment by greggirwin** [comment]
I'll give Peter a window to check in, then merge if nobody complains.

**Comment by greggirwin** [comment]
@hiiamboris do you want this merged, or am I holding off?

**Comment by hiiamboris** [comment]
@greggirwin Yes, better merge it until it diverges too much.

**Pull request merged**
