### PR TITLE
FEAT: String from block

### PR DESCRIPTION
**Pull request by Oldes**
With this change one can do:
```
red>> make string! ["a" "b"]
== "ab"
red>> make string! [a "b"]
== "ab"
red>> a: 1 make string! reduce [a "b"]
== "1b"
```

### CODE REVIEW

**Comment by Oldes** [comment]
@dockimbel It would be easy to add ```ajoin``` mezzanine or native, based on this feature, but I somehow feel you would not accept it without deep review of all possible string joining functions.

**Comment by dockimbel** [comment]
You are guessing right. ;-)

**Comment by Oldes** [comment]
Why is the type (re)setting needed?

**Comment by dockimbel** [comment]
Because you are allocating a new slot using `stack/push*` but not setting the value type and resetting the `/header` bits.

**Comment by Oldes** [comment]
@dockimbel isn't this enough? https://github.com/Oldes/Red/blob/5ef3c6b7b97ba9cc753f6a96340cedf69842dd85/runtime/datatypes/string.reds#L918

**Comment by dockimbel** [comment]
Ah sorry, yes it's right, github UI was hidding it from me, so I miss it...

image

**Comment by Oldes** [comment]
@dockimbel Ok.. must go to work now.. let me know, if you want me to do the size prediction later or if it's fine for now.

**Pull request closed without merging**
