### PR TITLE
FIX: OS-request-dir/dir and OS-request-file/file ignore string! values

### PR DESCRIPTION
**Pull request by endo64**

### CODE REVIEW

**Comment by dockimbel** [comment]
Thank you for the fix, @qtxie will review it.

**Comment by dockimbel** [comment]
@qtxie Can we merge this PR?

**Comment by dockimbel** [comment]
@endo64 Please rebase your PR, or create a new one in a separate branch to avoid other non-related commits showing up in the PR.

**Comment by endo64** [comment]
I'm closing this PR and made a clean PR #3138

**Pull request closed without merging**
