### PR TITLE
FIX: 4900 (fmod platform discrepancy leads to modulo ambiguity)

### LINKED ISSUE #4900: `fmod` platform discrepancy leads to modulo ambiguity
**Describe the bug**
```
Red/System []
probe fmod 123.0 1.0 / 0.0
```
Result on Windows:
```
-1.#IND.0
```
On Linux:
```
123.0
```

So it gets carried into Red code:
```
>> 123 % 1.#inf
== 1.#NaN        ;) Windows
== 123.0         ;) Linux
```

**Expected behavior**

I think Linux result makes more sense. Whatever the dividend is, infinite divisor is still bigger than it, so the remainder should be the dividend.

**Platform version**
```
Red 0.6.4 for Windows built 12-May-2021/6:12:03+03:00  commit #cebd5b9
Red 0.6.4 for Linux built 11-May-2021/6:20:25+03:00  commit #81d0416
```

### PR DESCRIPTION
**Pull request by hiiamboris**
Fixes #4900 by following GCC semantics for x % infinity.

Also removes dead code.

### CODE REVIEW

**Comment by dockimbel** [comment]
@qtxie Please review this PR.

**Review by qtxie — APPROVED** [review]

**Comment by dockimbel** [comment]
I get an error in the tests suite after merging this PR in master:
```
Compiling C:\Dev\Red\tests\source\units\auto-tests\run-all-comp2.red ...
...using libRedRT built on 22-Jul-2021/17:44:39
...compilation time : 2681 ms

Target: MSDOS 

Compiling to native code...
*** Compilation Error: argument type mismatch on calling: red/float/push64 
*** expected: [integer!], found: [struct! [
        header [integer!] 
        data1 [integer!] 
        data2 [integer!] 
        data3 [integer!]
    ]] 
*** in file: %/C/Dev/Red/tests/source/units/auto-tests/run-all/regression-test-red.red 
*** at line: 363 
*** near: [
    stack/unwind 
    natives/nan?* true 
    stack/unwind 
    f_--assert 
    stack/unwind 
    stack/reset 
    stack/mark-func
]
```
@hiiamboris Can you reproduce it?

**Comment by hiiamboris** [comment]
Found it:
```
Red [] -1.#nan
```
`red -c 1.red`:
```
Compiling to native code...
*** Compilation Error: red/float/push64 is missing an argument
*** in file: %/D/devel/red/red-src/red/1.red
*** at line: 353
*** near: [#user-code]
```

**Comment by qtxie** [comment]
`-1.#nan`, I think the lexer should report it as a syntax error.

**Comment by dockimbel** [comment]
I've let both compiler and runtime lexer accept `-1.#nan` and normalize it as `1.#NaN`. Does any negative NaN exists in IEEE-754 standard? Do other mainstream languages have a concept of negative NaN?

**Comment by hiiamboris** [comment]
https://stackoverflow.com/questions/21349847/positive-vs-negative-nans
We should just ignore the sign and treat all nans equally, and mold as just `1.#NaN`.

**Comment by dockimbel** [comment]
Then it's how it works now (after my yesterday's fix).

**Comment by greggirwin** [comment]
I agree with @qtxie that it should be an error. We're talking about the lexical form here, not the internal representation of NaN, right? What value does it add to let people write it as negative, if it has no meaning?

**Comment by hiiamboris** [comment]
[Postel's Law?](https://github.com/red/red/issues/4863#issuecomment-820621919) ;)

**Comment by greggirwin** [comment]
It has its costs. Everything we allow is something we can't disallow later. Postel's Law is nice when you're talking about some things, absolutely (e.g. variants of protocols or formats). In the other ticket, note that I added "That doesn't mean being too liberal of course.", just like the old axiom "Be open minded, but not so open that your brains fall out."

So I'll ask my question again: what value does it add, when it *looks* like it has meaning, but doesn't?

**Comment by hiiamboris** [comment]
I'm not against forbidding it either.

**Comment by dockimbel** [comment]
So if all are in agreement to forbid that lexical form, I'll do the change.

**Pull request merged**
