### PR TITLE
Add cli argument to usage

### PR DESCRIPTION
**Pull request by dander**
Updates the usage text for both README file and usage.txt to mention the --cli flag.

I also made a separate commit to remove some trailing whitespace that seemed extraneous.

I'm creating this PR from the Github app for the first time, so hopefully I haven't screwed anything up.

### CODE REVIEW

**Comment by dockimbel** [comment]
@dander Thanks! But the PR cannot be merged as shown above, it seems you need to update your codebase to latest red/red commit, and re-submit the PR.

**Comment by dander** [comment]
Looks like you merged the PR already, so I guess everything was okay?

I saw that warning, but I had already resolved a conflict in the usage.txt file, so I didn't know what it was complaining about. Any idea what was going on? Maybe I did things in a funky order or something.

Should I try to rebase my changes next time so the commit log is cleaner?

**Comment by dockimbel** [comment]
I'm not sure either, but yes, you should rebase before submitting a PR. Also if you could merge your commits into one next time, it would be even better (unless there is a good reason to keep changes separated in several commits).

**Comment by dander** [comment]
My rational for having separate commits was to make the substantial one clearer, and I was also not sure if you'd want to take the whitespace stuff, so I figured that would make it easier to exclude or cherry pick.
I'm not very used to the git workflow. Thanks for taking the time to help. Hopefully I'll be able to make some more meaningful contributions in the future :)

**Comment by dockimbel** [comment]
Valid points. Though, it is easier for us if we don't have to filter out the PR content in details, so better discuss with us on Gitter about the content before submitting, if you're unsure about some changes being accepted. :-)

**Pull request merged**
