### PR TITLE
CHORE: refactor `wait` native

### PR DESCRIPTION
**Pull request by loziniak**
removes OS dependency from `runtime/natives.reds`

### CODE REVIEW

**Comment by 9214** [comment]
[General contribution guidelines](https://github.com/red/red/wiki/%5BDOC%5D-Contributor-Guidelines#general-contribution-guidelines), p. 5.

**Comment by loziniak** [comment]
It's a refactor, so neither a FIX, nor FEAT. Which one should I use?

**Comment by hiiamboris** [comment]
I'm unsure `if time < 1.0 [time: 1.0]` is a good change. A value of zero is used in Windows to yield the thread's remaining time slice to other threads and may return immediately. Why forbid it?

**Comment by greggirwin** [comment]
FEAT or FIX is sometimes a hard choice. Let's call this a FIX, since it's not adding anything new, just improving the implementation.

**Comment by dockimbel** [comment]
What is this  "CHORE:" prefix doing in the commits history?

**Comment by loziniak** [comment]
@greggirwin it's already merged, so probably too late for that? I'll try to remember that next time. Thanks.

**Pull request merged**
