### PR TITLE
FIX: #5559 mold/all for unset values.

### PR DESCRIPTION
**Pull request by greggirwin**
https://github.com/red/red/issues/5559

### CODE REVIEW

**Comment by dockimbel** [comment]
Many tests are failing after that change. `form <unset>` should return an empty string, but `mold` should return `unset` otherwise that would cause some troubles (and break compatibility with Rebol):

```
>> mold reduce [1 () 2]
== "[1 unset 2]"
```

**Comment by greggirwin** [comment]
Ah, because there's no negative offset, got it.

**Comment by greggirwin** [comment]
Been way too long since I've been in R/S-land. Even if I don't use `form` I have to do something like this, right (or just return `part` directly)?
```
string/concatenate-literal buffer ""
part
```
Which still errors here.

**Comment by greggirwin** [comment]
Doh! Think I have my head on straight now.

**Pull request closed without merging**
