### PR TITLE
NEW: change function

### PR DESCRIPTION
**Pull request by SteeveGit**

### CODE REVIEW

**Comment by dockimbel** [comment]
Great, thanks!

**Comment by fvanzeveren** [comment]
Please note that this implementation is wrong.
Does not handle properly the /dup refinement, as well as some /only test cases.
Please, test your code before submitting. 

Running the complete test scenarii [here](https://gist.github.com/fvanzeveren/2a23d0af2b443d87dbe28ca15e74c72c) result in these tests cases failing

`** Assertion failed for: [equal? [1 2 3 1 2 3 1 2 3 1 2 3 m n] head change/dup [a b c d e f g h i j k l m n] [1 2 3] 4]
** Assertion failed for: [equal? [[1 2 3] [1 2 3] [1 2 3] [1 2 3] e f] head change/only/dup [a b c d e f] [1 2 3] 4]
** Assertion failed for: [equal? [1 2 3 [4 5] 6 1 2 3 [4 5] 6 1 2 3 [4 5] 6 1 2 3 [4 5] 6 u v] head change/dup [a b c d e f g h i j k l m n o p q r s t u v] [1 2 3 [4 5] 6] 4]
** Assertion failed for: [equal? [[1 2 3 [4 5] 6] [1 2 3 [4 5] 6] [1 2 3 [4 5] 6] [1 2 3 [4 5] 6] e f] head change/only/dup [a b c d e f] [1 2 3 [4 5] 6] 4]
** Assertion failed for: [equal? [12 12 12 d e] head change/dup [a b c d e] 12 3]
** Assertion failed for: [equal? [12 12 12 d e] head change/only/dup [a b c d e] 12 3]
** Assertion failed for: [equal? ["12" "12" "12" d e] head change/dup [a b c d e] "12" 3]
** Assertion failed for: [equal? ["12" "12" "12" d e] head change/only/dup [a b c d e] "12" 3]
** Assertion failed for: [equal? [123.10.2.3 123.10.2.3 123.10.2.3 d e] head change/dup [a b c d e] 123.10.2.3 3]
** Assertion failed for: [equal? [123.10.2.3 123.10.2.3 123.10.2.3 d e] head change/only/dup [a b c d e] 123.10.2.3 3]
** Assertion failed for: [equal? "123123123jklmnopqrstuvwxyz" head change/dup "abcdefghijklmnopqrstuvwxyz" [1 2 3] 3]
** Assertion failed for: [equal? "123defghijklmnopqrstuvwxyz" head change/only "abcdefghijklmnopqrstuvwxyz" [1 2 3]]
** Assertion failed for: [equal? "123123123jklmnopqrstuvwxyz" head change/only/dup "abcdefghijklmnopqrstuvwxyz" [1 2 3] 3]
** Assertion failed for: [equal? "123 4 56123 4 56123 4 56yz" head change/dup "abcdefghijklmnopqrstuvwxyz" [1 2 [3 4 5] 6] 3]
** Assertion failed for: [equal? "123 4 56ijklmnopqrstuvwxyz" head change/only "abcdefghijklmnopqrstuvwxyz" [1 2 [3 4 5] 6]]
** Assertion failed for: [equal? "123 4 56123 4 56123 4 56yz" head change/only/dup "abcdefghijklmnopqrstuvwxyz" [1 2 [3 4 5] 6] 3]
** Assertion failed for: [equal? "123123123jklmnopqrstuvwxyz" head change/dup "abcdefghijklmnopqrstuvwxyz" 123 3]
** Assertion failed for: [equal? "123defghijklmnopqrstuvwxyz" head change/only "abcdefghijklmnopqrstuvwxyz" 123]
** Assertion failed for: [equal? "123123123jklmnopqrstuvwxyz" head change/only/dup "abcdefghijklmnopqrstuvwxyz" 123 3]
** Assertion failed for: [equal? "123123123jklmnopqrstuvwxyz" head change/dup "abcdefghijklmnopqrstuvwxyz" "123" 3]
** Assertion failed for: [equal? "123defghijklmnopqrstuvwxyz" head change/only "abcdefghijklmnopqrstuvwxyz" "123"]
** Assertion failed for: [equal? "123123123jklmnopqrstuvwxyz" head change/only/dup "abcdefghijklmnopqrstuvwxyz" "123" 3]
** Assertion failed for: [equal? "123.10.2.3123.10.2.3uvwxyz" head change/dup "abcdefghijklmnopqrstuvwxyz" 123.10.2.3 2]
** Assertion failed for: [equal? "123.10.2.3klmnopqrstuvwxyz" head change/only "abcdefghijklmnopqrstuvwxyz" 123.10.2.3]
** Assertion failed for: [equal? "123.10.2.3123.10.2.3uvwxyz" head change/only/dup "abcdefghijklmnopqrstuvwxyz" 123.10.2.3 2]
** Assertion failed for: [equal? [#"X" #"X" #"X" d e f] head change/dup [a b c d e f] #"X" 3]
** Assertion failed for: [equal? "XXXdef" head change/dup "abcdef" #"X" 3]`

Regards

**Comment by SteeveGit** [comment]
We’ve already discussed this fvanzeveren, but I will restate my points.
You assume we should completely port the behaviour of R2 even the obvious flawed parts with no discussion whatsoever followed by rants of the type: “Please, test your code…noob! “ (I added noob, but It feels like it)
I don’t like the last part.
Don’t take me lightly when you already know that the said “bug” may be intended.

I will take an example:
In R2, change  and change/only when used on strings have the same behaviour which is a miss to my opinion. So instead, why not comply with the intended behaviour of /only ? And as a bonus, It takes less code to do such inside the change function.
You responded to me that even if it’s a miss, we should minimise the burden of coders who want to port their apps to Red. I’m ok with that, but not when they are obviously flawed because in those cases I’m pretty sure that they are never used by coders and even if, we should not encourage such misuse especially if we need to over-charge the red code just to comply.
It’s only my opinion and it can be argued against. I’m ok with that, and will simply accept it, if DocKimbel follows your position on this matter.

About the first pushed version. If you remember correctly, Dockimbel asked for it. And we don’t need perfect code right off the bat because we can patch it later. Something imperfect is still better than nothing. And your current version came later especially because you had to incorporate the neat parts of my proposal (your first draft was over 30 lines of code).

About your current proposal: You have a point about the /dup correct behaviour.
So, YOU are right, it’s not fully tested, Ah Ah (damn!)
But I would prefer a correction of the actual version of change. There’s no need to trash all the code and replace it with your own design (which is a little too much verbose IMO).

Finally, if collaborative work is impossible, you can push corrections yourself and try your chance.

**Comment by fvanzeveren** [comment]
Dear SteeveGit

Let's make things clear: you did not test your code, I did! And you know why? Because you were so arrogant and pretentious. You posted your non working four lines of code, despite the fact I gave you examples and warnings about what the tricks were. You did not collaborate, you just looked down on me telling me you remembered well how 'change works and that it was not a challenge to reduce the code by three. You even added, as you were talking to a child: "Ce ne serait pas te rendre service"... But I was ready to hear... And i did, i put into practice the only right comment you did: initialize the refinements. Later, when I told you that your four lines waere not working... do you remember your reaction? (you thumb down... arrogance, again!), despite the fact that the failing test cases were mentioned in the discussion even before you post your four lines of bugged and untested code. Sorry, I know what collaboration is: respect your interlocutor and pay attention to what she/he says. Do you understand that? Conclusion of all this funny episode: it took you 7 iterations to go from 4 lines of non working code to 9 lines of still not working code. And if you almost succeeded to produce something decent, it is only because i was testing your code and reporting bugs to you. Meanwhile, it took me 4 iterations to go to 26 lines of (better) working code to 9 lines of fully working code. Just because I analyse the problem and test my solution myself.
Collaboration is NOT polluting discussions with untested code and certainly not submitting such a code to Doc for inclusion into RED.

By the way, my implementation is not more verbose than yours, but it just works.
And your discussion about whether the rebol change version is right or not is not applicable. The statement of work was to reproduce the change function. Full stop!

Cheers

**Comment by SteeveGit** [comment]
Ok, I see now where you come from and understand better your reaction. It's really a shame, it came to a huge pile of resentment between us. Next time, I hope we will tell each other when our attitudes are over the top and early, to prevent such mess.

**Comment by fvanzeveren** [comment]
Steeve,
That ok now, let's move on sth more constructive.

By the way, I do agree on your point regarding the behaviour of 'only with string. But then, it should be escalate to Doc that 'insert is doing the same "weird" behaviour:
`red>> head insert/only "abcd" [1 2 3 [4 5] 6]`
`== "1234 56abcd"`

**Pull request merged**
