### PR TITLE
switch qsort to pdqsort

### PR DESCRIPTION
**Pull request by bitbegin**

### CODE REVIEW

**Comment by bitbegin** [comment]
* transplant from `https://github.com/stjepang/pdqsort`
* bench code `https://github.com/bitbegin/red/blob/pbqsorttest/sortbench.red`

bench result:

```
 .\console.exe .\sortbench.red
1000000                         qsort                           pbqsort
shuffled-int                    441ms                   528ms
shuffled-16-values-int                  89ms                    127ms
all-equal-int                   24ms                    14ms
ascending-int                   57ms                    15ms
descending-int                  72ms                    66ms
pipe-organ-int                  363ms                   436ms
push-front-int                  389ms                   38ms
push-middle-int                 235ms                   27ms
```

**Comment by bitbegin** [comment]
https://github.com/bitbegin/red/commit/ce486ddf4d85b1d2c814be1e220e15d016bb2d9e

**Comment by qtxie** [comment]
The `pdqsort` in Red is much slower than expected in the benckmark. That is because it highly relys on the optimization of the compiler. We'll merge it once we have an optimization layer in Red/System.

FYI. Here are some benchmark reports compare `pdqsort` and `qsort` in C++.
[Round 1] https://gist.github.com/qtxie/f6e77a1d09491feb727340f3af8b522f
[Round 2] https://gist.github.com/qtxie/8accc4d2ac9f872eb74cddd42042928a
[Round 3] https://gist.github.com/qtxie/974420c48d1c9f7011e9441f668e9b46

**Comment by dockimbel** [comment]
I'll close this PR. It can be submitted again once we get the optimizing backend, if still relevant.

**Pull request closed without merging**
