### PR TITLE
FEAT: adds remove/key for series.

### PR DESCRIPTION
**Pull request by qtxie**

### CODE REVIEW

**Comment by qtxie** [comment]
Seems travis timeout.

**Comment by greggirwin** [comment]
I merged this, but should `/skip` also be implied. Right now it isn't. That is, if the `key` part implies a key-value model, it should use `/skip 2` as well.
```
>> blk: [a b c d e f]
== [a b c d e f]
>> remove/key blk 'b  ; I think of 'b as a value, not a key here
== [a d e f]
```

**Comment by hiiamboris** [comment]
`remove/key/part blk 'b 2` ?

**Comment by greggirwin** [comment]
Don't need `/part` there, but then you're also adding `/skip` to `remove`, and I'd end up writing a wrapper for that line as I have in the past. The redundancy of having to say `2` twice is ugly and error prone.

**Pull request merged**
