### PR TITLE
Small improvement of help message and addition of a left logical shift operator

### PR DESCRIPTION
**Pull request by lkppo**

### CODE REVIEW

**Comment by dockimbel** [comment]
Thanks for your PR. They are many good fixes there, though, putting all the commits in one PR makes it difficult to process, as some changes are not needed. 

For example, `shift-logical-left` is exactly the same as `shift-left`, so there is no need for it. Another change that will be rejected is adding help strings to `shift-right`, `shift-left`, `shift-logical` routines, as those routines are not meant for end users, but just as intermediary routines for the shifting operators. Therefore, they should not be documented.

If you could remove the two commits about bitwise operators from the PR, I would be glad to accept it.

**Comment by lkppo** [comment]
I reverted the two last commits about shift operators.

**Comment by dockimbel** [comment]
Thank you! I would like to merge it now, but it has now some conflicts. Could you please rebase your PR with latest commits from master?

**Comment by lkppo** [comment]
PR rebased.

**Comment by dockimbel** [comment]
Sorry, didn't merge it in time. Could you please rebase it again? TIA.

**Comment by lkppo** [comment]
Ok, I have rebased, hoping not to have done anything stupid. You have moved some functions so I will have to make a other pull-request.

**Comment by lkppo** [comment]
Yes, but you have moved them to an other file, no ?

**Comment by lkppo** [comment]
I think I will delete my PR and rewite my changes. It's not a big deal.

**Comment by dockimbel** [comment]
Thanks, sorry for the trouble. :sweat_smile:

**Pull request closed without merging**
