### PR TITLE
FIX/FEAT: #3487 #3489 help-string and compose

### PR DESCRIPTION
**Pull request by greggirwin**
Apologies for unrelated commits in the PR.

### CODE REVIEW

**Comment by greggirwin** [comment]
Looks like quick-test wasn't enough. Need to see what's failing.

**Comment by greggirwin** [comment]
@PeterWAWood I changed the #include to use an absolute path, which solved finding the file, but I don't know what the relative pathing should be for other includes to make that work normally. However, even with that in place, `help-string` is not seen during a %run-all.r pass. I haven't tracked that down yet, and may not spend more time on it now. I stubbed those tests out in the meantime.

**Comment by greggirwin** [comment]
@PeterWAWood, any more thoughts on this?

**Comment by PeterWAWood** [comment]
@greggirwin I'm not sure why you are having path problems with including help.red.

I added the following lines to `functions-test.red` on the `master` branch to check the `#include`:
```text
#include  %../../../environment/console/help.red
===start-group=== "help-ctx"
 	--test-- "help-ctx-1"
 		--assert help-ctx/DOC_SEP == "=>"
===end-group===
```
Here are the results:
```text
peter$ rebol -qws quick-test/run-test.r tests/source/environment/functions-test.red
Quick-Test v0.12.0
Running under REBOL 2.7.8.2.5
~~~started test~~~ functions
===group=== path-thru tests
--test-- path-thru test FAILED**************
~~~finished test~~~  functions
  Number of Tests Performed:      92
  Number of Assertions Performed: 134
  Number of Assertions Passed:    133
  Number of Assertions Failed:    1
****************TEST FAILURES****************
```
 How are you compiling the test when you get the paths issues?

**Comment by greggirwin** [comment]
If I just run a single test file, it's fine. It's when I do `do %tests/run-all.r` in a REBOL console that I get the failure.
```
>> do/args %run-test.r to-rebol-file "c:\dev\greggirwin\red\tests\source\environment\functions-test.red"
Script: "Builds and Runs a single Red/System Tests" (none)
Script: {Simple testing framework for Red and Red/System programs} (none)
Script: "Untitled" (none)
Quick-Test v0.12.0
Running under REBOL 2.7.8.3.1
~~~started test~~~ functions
~~~finished test~~~  functions
  Number of Tests Performed:      102
  Number of Assertions Performed: 146
  Number of Assertions Passed:    146
  Number of Assertions Failed:    0
```
```
>> cdr "C:\dev\greggirwin\red\"
== %/C/dev/greggirwin/red/
>> do %tests/run-all.r
Script: "Builds and Runs the Red Tests" (none)
checking to see if interpreter test files need generating
1 files were generated
Quick-Test v 0.12.0
REBOL  2.7.8.3.1
This test started at 5-Aug-2018/13:19:33.71-6:00
Red Test Suite

ok - lexer...........................................29 / 29
ok - lexer-auto......................................18 / 18
ok - unicode.........................................67 / 67
ok - preprocessor tests..............................22 / 22
ok - run-all-comp1.red.............................4039 / 4039
ok - run-all-comp2.red.............................6156 / 6156
** - run-all-interp*red*******************************0 / 1 **
ok - tools............................................7 / 7
ok - Red print........................................9 / 9
ok - Red run time errors..............................8 / 8
ok - Red compile errors...............................1 / 1

** - Red Test Suite*******************************10356 / 10357 **
       in 0:01:57.221

The test finished at 5-Aug-2018/13:21:30.931-6:00
The test output was logged to /C/dev/greggirwin/red/quick-test/quick-test.log
hit enter to finish

== 1
```

**Comment by PeterWAWood** [comment]
@greggirwin What did the quick-test.log show. The 0/1 suggest that run-all-interp.red either did not compile or crashed (segfault etc.). 

I suspect the problem is that the `make-run-all.r` script is not copying the include of help.reds. None of the other tests include other source files.

For me, the best solution would be to put the tests of `help.red` into a `help-test.red` file.

**Comment by greggirwin** [comment]
It said it couldn't find the include file, with the relative path.

**Comment by PeterWAWood** [comment]
@greggirwin I now understand the issue, the relative path is correct when the program is compiled but when the test is run from the quick-test/runnable directory, the runtime will resolve the relative path differently.

I could come up with a fix to the code that generates the interpreter tests so that any #include, if place directly below the file header, is processed by the compiler rather than the interpreter. 

It is a problem of having code that is going to be both compiled and interpreted. I don't think that there is an easy answer until we have modules.

**Comment by greggirwin** [comment]
Moved (stubbed) tests, and CI didn't time out. @PeterWAWood OK to merge?

**Comment by PeterWAWood** [comment]
@greggirwin Looks good to me

**Pull request merged**
