### PR TITLE
FIX: TO-CSV can encode block of maps/object properly

### PR DESCRIPTION
**Pull request by rebolek**
When fixing #4424 I found other problem. So here's a fix for that one.

### CODE REVIEW

**Comment by qtxie** [comment]
It's weird that this csv fix make view test failing. https://github.com/red/red/runs/656824799
@rebolek @hiiamboris

**Comment by greggirwin** [comment]
Indeed. All other tests passed, hence my merge. GH isn't loading the failure for me to see right now.

**Comment by rebolek** [comment]
@qtxie weird indeed could be the previous MR that does `unset 'l` to clean up after itself? Because that's the only thing I can think of as a possible reason for the problem, there's nothing special in this MR.

**Comment by hiiamboris** [comment]
The artifact says:
```
***Starting*** Red/View Test Suite
~~~started test~~~ base-self-test
===group=== to-image check
--test-- tic-5 to-image of an image font alpha FAILED**************
~~~finished test~~~  base-self-test
  Number of Tests Performed:      105
  Number of Assertions Performed: 493
  Number of Assertions Passed:    492
  Number of Assertions Failed:    1
****************TEST FAILURES****************



***Finished*** Red/View Test Suite
No of tests   105
No of asserts 493
Passed        492
Failed        1
***TEST FAILURES***

```
Must be some random glitch. Let's see if it repeats.

**Comment by 9214** [comment]
@qtxie at least 2 tests in this group are always failing locally, so I don't think it's related.

**Comment by hiiamboris** [comment]
@9214 care to tell me which ones?

**Comment by hiiamboris** [comment]
Anyway, I can't reproduce "tic-5" fail on W7. Must be one of the heisenbugs.

**Comment by qtxie** [comment]
The bug was magically gone in commit 6aff3bc7f4540c5656714929f8062ab848f48420.

**Comment by 9214** [comment]
@hiiamboris 
```
~~~started test~~~ base-self-test
===group=== text alignment check
--test-- #3725 part 1 FAILED**************
--test-- #3725 part 1 FAILED**************
~~~finished test~~~  base-self-test
  Number of Tests Performed:      105
  Number of Assertions Performed: 493
  Number of Assertions Passed:    491
  Number of Assertions Failed:    2
****************TEST FAILURES****************
```

**Comment by hiiamboris** [comment]
Hmm. I guess `base` and `draw` on W10 render text with a noticeable offset then. @9214 Does it show you the images diff? Is it some 1 pixel miss or a real issue on W10?

**Comment by 9214** [comment]
@hiiamboris 
Capture
Capture2

**Comment by hiiamboris** [comment]
Thanks! I'll change this test to text box geometry measurement then.

**Pull request merged**
